############################
##  === [ EASY WARP ] === ##
############################

# Name displayed in messages sent to player from plugin.
# ex. [server-name] You have been warped.
server-name: "&2&lLõimud > "


#============================================================================================================================#
#============================================================================================================================#
#============================================================================================================================#


#Variables:
#
#{delay}
#{name}
#{display}
#{node}
#{command}

#{page}
#{pages}

#{target}

#Messages to be sent
messages:
  warp:
    other: "&aSa viisid &c{target}&a &c{warp} lõimu."
    cancelled: "&cTeleportimine on katkestatud."
    completed: "&aSind teleporditi lõimu {warp}."
    delayed: "&eSind teleporditakse lõimu &l{delay} &esekundi pärast."
    removed: "&aLõim {warp} on eemaldatud."
    set: "&aLõim {warp} on tehtud."
    list: "&e&lLõimude nimekiri ({page}/{pages}):"
    no-permission:
    - "&cViga: Sul ei ole selle lõimu jaoks volitusi."
    - "&c -> Et näha kasutatavaid lõime, kasuta /lõimud"
  error:
    illegal-char: "&cSelline nimi on ebasobiv."
    no-warp:
    - "&cSellist lõimu pole olemas."
    - "&eLõimude vaatamiseks kasuta käsku /lõimud."
    no-warp-given:
    - "&cKasutamine: /lõim <nimi>"
    - "&eLõimude vaatamiseks kasuta käsku /lõimud."
    no-permission: "&cSul pole selleks piisavalt õigusi."
    no-page: "&cKasutamine: /lõimud <nr>"
    no-player: "&cViga: Mängjat ei leitud."
    not-player: "&cViga: Sa pead olema mängja, et seda teha."
    cannot-overwrite: "&cSellise nimega lõim on juba olemas."
  config:
    reloaded: "&aKonfiguratsjoon taaslaetud."

#Example of multi-lined message
#  example:
#  - This line comes first
#  - Then this one
