messages:
  prefix: '&2&lEhita > '
  no-permission: '&cSul ei ole piisavalt volitusi!'
  no-console: '&cSeda käsku saab kasutada ainult mängus.'
  disabled: '&cSeda ei saa loomingulises moodis teha!'
  disabled-interact: '&cSa ei saa seda teha, sest see on pärit loomingulisest moodist.'
  reloaded: '&aKonfiguratsjoon on taaslaetud!'
  db-load: '&eLaeme andmeid andmebaasist...'
  db-save: '&eSalvestame andmed andmebaasi...'
  db-added: '&eLisatud %blocks% uute asjade andmebaasi.'
  db-removed: '&eKustutatud %blocks% vana ese andmebaasist.'
  db-deleted: '&eAndmebaas eemaldatud. Serveri restart on vajalik.'
  db-loaded: '&eLaetud %blocks% kast andmebaasi!'
  db-done: '&aValmis! Took %mills%ms'
  creative-on: '&aLoominguline mood sees!'
  creative-off: '&aLoominguline mood väljas!'
  wrong-convert: '&cVale kasutus: /rc convert <cc|gmi|sql>'
  wrong-block: '&cÕige kasutus: /rc block <add|remove|info|stats>'
  cancel: '&cKatkestatud!'
  block-add: '&aRight-click a block/entity you want to add to the database. Type "/rc block add" again to cancel.'
  block-added: '&aAdded %material% to the database!'
  block-remove: '&aRight-click a block/entity you want to remove from the database. Type "/rc block remove" again to cancel.'
  block-removed: '&aRemoved %material% from the database!'
  block-info: '&aRight-click a block/entity you want to know more about. Type "/rc block info" again to cancel.'
  block-info-true: '&aBlock/entity %material% is placed in creative mode!'
  block-info-false: '&aBlock/entity %material% is not placed in creative mode.'
  disabled-region: '&cYou can''t do that outside the allowed region.'
  block-stats: '&eTotal creative placed blocks and entities: %total%'
  disabled-creature: '&cYou can''t do that, because a part of the creature was placed in creative mode.'
